### ISSUE TITLE
Can not send more than MAX_CONNECTIONS at once

### ISSUE THREAD

**Issue by sisoje** [AndrewBarba/apns2#17]
I have an array of notifications and it fails to send them if there is more than MAX_CONNECTIONS in array.

**Comment by sisoje** [comment]
Here is my code:
`    client.send(notifications)
    .then(() => {
        context.log('notifications done', notifications.length)        
        context.done()
    })
    .catch(err => {
        context.log('notifications done', notifications.length)        
        context.log('error', err)
        context.done()
    })`

**Comment by sisoje** [comment]
When executing nothing happens - no success no error

**Comment by sisoje** [comment]
will i have trouble if i put MAX_CONNECTIONS to 1000?

**Comment by AndrewBarba** [comment]
Definitely don't increase `MAX_CONNECTIONS` to 1000, I'm looking into this and will report back

**Comment by sisoje** [comment]
ok thanks

**Comment by AndrewBarba** [comment]
I found the issue, pushing a new version now

**Comment by AndrewBarba** [comment]
Fixed in v4.0.4: https://github.com/AndrewBarba/apns2/releases/tag/4.0.4

**Comment by dimaqq** [comment]
Hello, I'm a contributor to https://github.com/HENNGE/aapns and I wonder how this project solved this particular issue.
IIRC, when the connection is created, the client has to assume "max connections", typically `100`, while the server is going to lower this to `1` very quickly afterwards. It does so because when authentication is done by a token, there's no authentication until the first request. After first request passes authentication check, the server will re-instate reasonable "max connections".
I solved this by artificially restricting connection concurrency until one response indicates OK.
I'm curious what approach this library takes.
