### ISSUE TITLE
Use with Serverless infrastructure such as AWS Lambda?

### ISSUE THREAD

**Issue by bfelbo** [AndrewBarba/apns2#41]
Hi, thanks for a great library. We're currently using version 8.5 on AWS Lambda and it's working well. However, I saw that in 9.1 you've implemented "Keeps socket alive with ping request every 60s". It's unclear to me how this'll work in a serverless context such as AWS Lambda, where each lambda will be destroyed/frozen before 60 seconds has passed. In the frozen scenario, the lambda will be awoken again up to 15 minutes later and re-used to avoid any cold boots.

Does this library work fine w/o the ping requests and would it be possible to add an option to disable it?

**Comment by AndrewBarba** [comment]
Hey @bfelbo, I use this lib exclusively on AWS Lambda and can ensure you the ping interval doesn't have any negative effect. Lambda will freeze the container but it will maintain connections so on subsequent invocations those connections will remain active (assuming you create the connections outside the main request handler). This lib will simply send pings every 60s to further maintain those connections. When the function wakes up, if its been more than 60s since the last invocation, then the client will send a ping to attempt to maintain the connection. If the connection has been closed then the client will be recreated the next time you use it

**Comment by AndrewBarba** [comment]
With all the said, I just released v9.2 which lets you disable the ping interval entirely if you wish to do so: https://github.com/AndrewBarba/apns2/releases

**Comment by bfelbo** [comment]
Perfect, thanks!
